config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  resources :users
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/user.rb
class User < ApplicationRecord
  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :roll_no, uniqueness: true

  def get_full_name
    "#{first_name} #{last_name}"
  end

  def get_us_name
    "#{last_name} #{first_name}"
  end

  def get_full_address
    [house_no, block, area, city, country].select(&:present?).join ', '
   end

  # def self.get

  # end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def create
     @user = User.create(user_params)

     if @user.save
        redirect_to :action => 'index'
     else
        render :action => 'new'
     end

  end

  def edit
    @user = User.find(params[:id])
  end


  def update
     @user = User.find(params[:id])

     if @user.update(user_params)
        redirect_to :action => 'show', :id => @user
     else
        render :action => 'edit'
     end

  end

  def destroy
    User.find(params[:id]).destroy
    redirect_to :action => 'index'
  end

  private

  def user_params
     params.require(:user).permit(
      :first_name,
      :roll_no,
      :last_name,
      :house_no,
      :block,
      :area,
      :city,
      :country, 
      )
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Railsapp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/users/edit.html.erb
<h3>Update User Details</h3>
<%= form_with model: @user do |form| %>
  <%= form.text_field :first_name, placeholder: "First Name" %>
  <%= form.text_field :last_name, placeholder: "Last Name" %>
  <%= form.text_field :roll_no, placeholder: "Roll Number" %>
  <%= form.text_field :house_no, placeholder: "House No" %>
  <%= form.text_field :block, placeholder: "Block" %>
  <%= form.text_field :area, placeholder: "Area" %>
  <%= form.text_field :city, placeholder: "City" %>
  <%= form.text_field :country, placeholder: "Country" %>
  <%= form.submit %>
<% end %>

app/views/users/index.html.erb
<h1>User List<h1>
<ul>
  <% @users.each do |user| %>
    <li>
      <div style="display:flex; flex-direction: column; justify-content: space-between;width:50%;" >
        <div style="display:flex; flex:1; flex-direction: column">
            <div style="display:flex"><span style="flex:1">Name: </span><%= user.first_name %></div>
            <div style="display:flex"><span style="flex:1">Roll Number: </span><%= user.roll_no %></div>
            <div style="display:flex"><span style="flex:1">Address: </span><%= user.get_full_address %></div>
        </div>
        <div style="display:flex; justify-content: space-between;width: 50%;min-width:fit-content;" >
          <%= link_to 'show', user_path(user) %>
          <%= link_to 'edit', edit_user_path(user) %>
          <%= link_to 'delete', user_path(user), data: {turbo_method: :delete} %>
          <!-- <%= button_to 'delete', user_path(user), method: :delete %> -->
        </div>
      </div>
    </li>
    <div style="width: 100%; height: 2px; background-color: lightgrey "></div>
  <% end %>
</ul>
<%= link_to "Add a new user", new_user_path %>

app/views/users/new.html.erb
<h3>Create a User</h3>
<%= form_with model: @user do |form| %>
  <%= form.text_field :first_name, placeholder: "First Name" %>
  <%= form.text_field :last_name, placeholder: "Last Name" %>
  <%= form.text_field :roll_no, placeholder: "Roll Number" %>
  <%= form.text_field :house_no, placeholder: "House No" %>
  <%= form.text_field :block, placeholder: "Block" %>
  <%= form.text_field :area, placeholder: "Area" %>
  <%= form.text_field :city, placeholder: "City" %>
  <%= form.text_field :country, placeholder: "Country" %>
  <%= form.submit %>
<% end %>

app/views/users/show.html.erb
<h1><%= @user.get_full_name %></h1>
<h2><%= @user.roll_no %></h4>
<h3><%= @user.get_full_address %></h4>
<%= link_to "Back to list page", users_path %>